// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tijwyvffmwwiadmqtyer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpand5dmZmbXd3aWFkbXF0eWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjI0NzUsImV4cCI6MjA2NjEzODQ3NX0.Ry6VLVcwHzTrUdiDw5n4P5qlaxAQPRpr4ImW4ZqaMvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);